name: here_for_you_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.69.0
  dash_chat_2: ^0.0.21
  flutter_keyboard_visibility: ^6.0.0
  any_link_preview: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/icons/
    - lib/assets/images/
    - lib/assets/json/questions.json
  fonts:
    - family: fontmain
      fonts:
        - asset: lib/assets/fonts/Urbanist-Bold.ttf
