// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtopklILG-eabv1GIIr4uI2ZSulZv7oJc',
    appId: '1:190263192643:web:7baefd6ae5bf25d9baf8f6',
    messagingSenderId: '190263192643',
    projectId: 'hereforyou-59786',
    authDomain: 'hereforyou-59786.firebaseapp.com',
    storageBucket: 'hereforyou-59786.firebasestorage.app',
    measurementId: 'G-Y4XEJ5D1ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9DM8XR7qud-kOrhTv6p6BChK8qMu31JA',
    appId: '1:190263192643:android:54e1c978a3950ea5baf8f6',
    messagingSenderId: '190263192643',
    projectId: 'hereforyou-59786',
    storageBucket: 'hereforyou-59786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5HRp-pUflupoodI2ZgqgisOwujaOVpY8',
    appId: '1:190263192643:ios:d360767651e560f9baf8f6',
    messagingSenderId: '190263192643',
    projectId: 'hereforyou-59786',
    storageBucket: 'hereforyou-59786.firebasestorage.app',
    iosBundleId: 'com.aaruush.HereForYou.hereForYouApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5HRp-pUflupoodI2ZgqgisOwujaOVpY8',
    appId: '1:190263192643:ios:d360767651e560f9baf8f6',
    messagingSenderId: '190263192643',
    projectId: 'hereforyou-59786',
    storageBucket: 'hereforyou-59786.firebasestorage.app',
    iosBundleId: 'com.aaruush.HereForYou.hereForYouApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtopklILG-eabv1GIIr4uI2ZSulZv7oJc',
    appId: '1:190263192643:web:a1b686ebcf26ddcbbaf8f6',
    messagingSenderId: '190263192643',
    projectId: 'hereforyou-59786',
    authDomain: 'hereforyou-59786.firebaseapp.com',
    storageBucket: 'hereforyou-59786.firebasestorage.app',
    measurementId: 'G-LJQNS2BFTD',
  );

}